### ISSUE TITLE
Do not install docker anymore

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-images#106]
Because kubernetes will drop support for the dockershim (https://github.com/kubernetes/enhancements/issues/2221) with 1.24, and we default to containerd for shoots with k8s >= 1.19, it is safe to remove docker and solely install containerd once all clusters are >= 1.19.

Depends on https://github.com/gardener/gardener/issues/4673

**Comment by rfranzke** [comment]
https://github.com/gardener/gardener/issues/4673 is closed now :)

**Comment by majst01** [comment]
> [gardener/gardener#4673](https://github.com/gardener/gardener/issues/4673) is closed now :)

takes some weeks til we are at g/g 1.92 though :smiling_face_with_tear:
