### ISSUE TITLE
dhclient running on machines

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/metal-images#144]
```
root        1054  0.0  0.0   9500  5660 ?        Ss   14:12   0:00 /sbin/dhclient -4 -v -i -pf /run/dhclient.lan0.pid -lf /var/lib/dhcp/dhclient.lan0.leases -I -df /var/lib/dhcp/dhclient6.lan0.leases lan0
```
This can lead to strange behavior if frr-reload failed on a switch and dhclient is able to reach the DHCP server.
For example in one case, /etc/resolv.conf of a node was overwritten with the mgmt-server addresses:

```
nameserver 10.3.253.13
nameserver 10.3.253.29
```

**Comment by Gerrit91** [comment]
The general issue of having metal-core not being able to properly apply the FRR config is at least worth creating an issue, too.

**Comment by mwennrich** [comment]
closed with https://github.com/metal-stack/metal-images/pull/145
