### ISSUE TITLE
debian-10 reboot ends in UEFI shell

### ISSUE THREAD

**Issue by suckowbiz** [metal-stack/metal-images#16]
Integration tests run into an issue with Debian image. I am creating this issue to document this.

Expected behavior:
First reboot after installation results in a machine that is up and running.

Experienced behavior:
First reboot after installation breaks the machine. It boots into UEFI shell:

```
BdsDxe: failed to load Boot0001 "UEFI QEMU HARDDISK QM00005 " from PciRoot(0x0)/Pci(0x3,0x0)/Sata(0x0,0xFFFF,0x0): Not Found
BdsDxe: loading Boot0002 "EFI Internal Shell" from Fv(7CB8BDC9-F8EB-4F34-AAEA-3EE4AF6516A1)/FvFile(7C04A583-9E3E-4F1C-AD65-E05268D0B4D1)
BdsDxe: starting Boot0002 "EFI Internal Shell" from Fv(7CB8BDC9-F8EB-4F34-AAEA-3EE4AF6516A1)/FvFile(7C04A583-9E3E-4F1C-AD65-E05268D0B4D1)
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
      FS0: Alias(s):HD0a65535a1:;BLK1:
          PciRoot(0x0)/Pci(0x3,0x0)/Sata(0x0,0xFFFF,0x0)/HD(1,GPT,C12A7328-F81F-11D2-BA4B-00A0C93EC93B,0x800,0x95801)
     BLK0: Alias(s):
          PciRoot(0x0)/Pci(0x3,0x0)/Sata(0x0,0xFFFF,0x0)
     BLK2: Alias(s):
          PciRoot(0x0)/Pci(0x3,0x0)/Sata(0x0,0xFFFF,0x0)/HD(2,GPT,A4BC9994-8D21-4293-88AF-E5D6919657CD,0x96800,0x92D801)
     BLK3: Alias(s):
          PciRoot(0x0)/Pci(0x3,0x0)/Sata(0x0,0xFFFF,0x0)/HD(3,GPT,BFF47AA1-E8E7-42D7-8468-3C866B299339,0x9C4800,0x1F37DF)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell> 
```

Environment:
Integration test environment with Vagrant.
Testing tenant server image: debian-10 (https://images.metal-pod.io/debian/10/20200309/img.tar.lz4)'

**Comment by majst01** [comment]
Can we reproduce this on bare metal ?
One more ugly difference between ubuntu and debian.

**Comment by suckowbiz** [comment]
I could not reproduce that issue on bare metal.

```
root@debian-reboot-test:~# history
    1  ping heise.de
    2  uptime
    3  reboot
    4  history
root@debian-reboot-test:~# uptime
 12:08:49 up 1 min,  1 user,  load average: 0.28, 0.11, 0.04
```
Image

```
metalctl image ls
ID               	NAME             	DESCRIPTION      	FEATURES 
debian-10        	Debian 10        	Debian 10        	machine 	
[...]

metalctl image describe debian-10
changed: "2020-03-20T10:38:32.037Z"
created: "2020-03-19T14:39:59.901Z"
description: Debian 10
features:
  - machine
id: debian-10
name: Debian 10
url: http://images.metal-pod.io/metal-os/debian/10/20200317/img.tar.lz4
```

**Comment by suckowbiz** [comment]
Since the reboot behavior between Vagrant and bare metal is not the same I do not see much advantage in running an integration test that tests a reboot. I think this test should be disabled as long as we rely on Vagrant based tests.

**Comment by majst01** [comment]
I think we will need some form of integration tests done on bare-metal, vagrant is not capable to reflect all aspects, especially regarding ipmi, bios and other very hardware specific topics

**Comment by suckowbiz** [comment]
I am going to close this issue since the reported behavior is specific to a test environment and does not affect bare metal. Let's discuss bare metal tests offline.
