### ISSUE TITLE
firewall-policy-controller or droptailer wont start on firewall

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-images#19]
only one can be started, the other one dies with:

```
bpf: Failed to load program: Operation not permitted
```

Someone else also has these problems but no solution so far:

https://gehrcke.de/2019/09/running-an-ebpf-program-may-require-lifting-the-kernel-lockdown/

**Comment by mwennrich** [comment]
at least the debian worker machines are not in locked-down mode (so probably Debian firewall not either).

**Comment by majst01** [comment]
There is no difference in that perspective between debian and debian firewall.

**Comment by majst01** [comment]
sadly this also happens on a ubuntu based firewall, but much less frequent.
Found another bug report seeing the same:
https://github.com/iovisor/bcc/issues/2436
and:
https://bugzilla.redhat.com/show_bug.cgi?id=1813599

Doing some research on a ubuntu firewall, firewall-policy-controller is running, droptailer cant be started with systemctl start droptailer because of "operation not permitted". Running by hand with:

```
/bin/ip vrf exec vrf154 /usr/local/bin/droptailer-client
```
works ?

Inspecting what bpf calls are made with:

```
strace -ebpf /bin/ip vrf exec vrf154 /usr/local/bin/droptailer-client
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_CGROUP_SOCK, insn_cnt=6, insns=0x7ffc6d2392e0, license="GPL", log_level=1, log_size=262144, log_buf="", kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS}, 112) = 6
bpf(BPF_PROG_ATTACH, {target_fd=5, attach_bpf_fd=6, attach_type=BPF_CGROUP_INET_SOCK_CREATE, attach_flags=0}, 112) = 0
```

doing the same from within the systemd service gives:

```
strace[1982]: bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_CGROUP_SOCK, insn_cnt=6, insns=0x7ffc01ce0400, license="GPL", log_level=1, log_size=262144, log_buf="", kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS}, 112) = -1 EPERM (Operation not permitted)
```
more confusion, digging further

**Comment by majst01** [comment]
Found it ! BPF Troubleshooting guide (https://prototype-kernel.readthedocs.io/en/latest/bpf/troubleshooting.html) states: 
```
The eBPF maps uses locked memory, which is default very low. Your program likely need to increase resource limit RLIMIT_MEMLOCK see system call setrlimit(2).
```
Doing so in the systemd service with:
droptailer.service
```
[Unit]
Description=Droptailer
After=network.target

[Service]
LimitMEMLOCK=infinity
Environment=DROPTAILER_SERVER_ADDRESS=droptailer:50051
Environment=DROPTAILER_PREFIXES_OF_DROPS="nftables-metal-dropped: ,nftables-firewall-dropped: "
Environment=DROPTAILER_CLIENT_CERTIFICATE=/etc/droptailer-client/droptailer-client.crt
Environment=DROPTAILER_CLIENT_KEY=/etc/droptailer-client/droptailer-client.key
ExecStart=strace -ebpf /bin/ip vrf exec vrf154 /usr/local/bin/droptailer-client
Restart=always
RestartSec=10

[Install]
WantedBy=firewall-policy-controller.service
```

Solved the problem, droptailer starts.

**Comment by majst01** [comment]
once the networker pr is merged, update of networker in the images is required.

**Comment by Gerrit91** [comment]
So glad you found this out. Thanks for digging so deeply!
