### ISSUE TITLE
Ideas to improve development speed for firewall-controller

### ISSUE THREAD

**Issue by mwindower** [metal-stack/metal-images#38]
Current situation:
1. it's tedious to wait for metal-images to be build to test new firewall-controller versions
1. it's even more tedious to update production firewalls to use new firewall-controller versions (needs a complete firewall cycle)

Proposals to overcome these obstacles:
- run the firewall-controller as container with a kubelet and a static pod manifest: no access to an api-server is needed, but it's unclear how we overcome 2.
- run the firewall-controller as container with a kubelet and a static pod manifest URL: this can be located on S3 and is rechecked every 20 seconds
- let the firewall-controller reconcile itself

**Comment by majst01** [comment]
firewall-controller version could be a property of the firewall crd

**Comment by mwindower** [comment]
I'll move this issue over to the firewall-controller. With new firewall-controllers we have the opportunity to do it with the third approach: holding a firewall-controller version in the firewall crd and letting the firewall-controller reconcile itself.
