### ISSUE TITLE
Unable to up the installed VM on aarch64

### ISSUE THREAD

**Issue by jerald-jacob** [metal-stack/metal-images#47]
Hi team I'm facing the a problem that also reported. I'm working on aarch64 system and try to install android on it. it comes to the below behavior .
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
BLK2: Alias(s):
VenHw(93E34C7E-B50E-11DF-9223-2443DFD72085,00)
BLK0: Alias(s):
PciRoot(0x0)/Pci(0x2,0x0)
BLK1: Alias(s):
PciRoot(0x0)/Pci(0x3,0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell> bcfg boot dump -v

**Comment by Gerrit91** [comment]
Hi,

both maintainers of this repo are currently on vacation but maybe we can help you anyway.

I first need to ask for a little more information. In which context are you using the image? With metal-stack? Which version of metal-stack are you using? I guess this error would occur if either PXE boot is not working properly in your environment or changing the boot order after machine allocation did not work.

**Comment by majst01** [comment]
Hi @jerald-jacob ,

Our images are able to install OSes on x86_64 UEFI only at the moment. Can you please explain a bit more in detail what you want to achieve ?

**Comment by jerald-jacob** [comment]
Hi @majst01,

I want to Install android ARM on QEMU. But the final result is
```
 Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell>
```

**Comment by jerald-jacob** [comment]
**System Information** 
```

Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       4
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
BogoMIPS:                        166.66
L1d cache:                       512 KiB
L1i cache:                       768 KiB
L2 cache:                        8 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

**Comment by majst01** [comment]
Our bare-metal-as-a-service is currently meant to install kubernetes worker nodes and other general purpose linux server machines in the datacenter. I am not sure if you have the right application in mind while doing your tests.

**Comment by jerald-jacob** [comment]
We need to virtualize the ARM processor on our experiment, That's why we are using the A1 metal Instance. to virtualize the KVM or QEMU to install the arm based OS. I'm Successfully Installed the ARM Ubuntu on the QEMU. Now I'm trying to install the android arm the issue is happen. May I now ,the metal instance which support the Android ARM.

**Comment by Gerrit91** [comment]
What experiment?
What is an A1 metal instance? Are you talking about AWS? 

I honestly don't know if we are on the same page. Your questions are far beyond from what this project is about.

Please consider that this repository is part of a product called [metal-stack](https://metal-stack.io/) and the OS images built from this repository are meant to be run in the context of this software. We are a self-hosted cloud provider for bare metal. It is not about virtualization.
