### ISSUE TITLE
Implement the new auto logon

### ISSUE THREAD

**Issue by JanK-Cloud** [metal-stack/metal-images#95]
Change console logon to Bafin / Compliant conform autologin procedure, please.

**Comment by Gerrit91** [comment]
@JanK-Cloud Could you please add more specific information on what should be done? Otherwise this issue is stalling.

**Comment by majst01** [comment]
TODO:

- remove the console login prompt, autologon to the metal user instead
- add metal user to the wheel group and modify `/etc/sudoers` that `sudo -i` works without a password prompt

**Comment by michaelottofits** [comment]
i think the todos from @majst01  fully describe how the requirement should be implemented. 

goal was that `metalctl machine console` works automatically without user password input

**Comment by majst01** [comment]
closing with #103
